### ISSUE TITLE
[2기] 5주차 알고리즘 뱅크

### ISSUE THREAD

**Issue by hsik0225** [back-stage/WeekBack-Algorithm#8]
# 사이트별 개수 정책
|사이트|등급|취급 개수|
|---|---|---|
|백준|Bronze|1개|
||Silver|2개|
||Gold|4개|
||Platinum을 비롯한 그 이상|5개|
|프로그래머스|Level 1|2개|
||Level 2|3개|
||Level 3|4개|
||Level 4|5개|
||Level 5|6개|
|LeetCode|Easy|2개|
||Medium|4개|
||Hard|6개|
|Codility|Painless|1개|
||Respectable|2개|
|Goorm|Level 1 ~ 3|1개|
||Level 4 ~ 5|2개|

# 목표 개수
일주일에 **8개씩**

# 벌금
- 한 문제당 **500원** 차감
- [WeekBack](https://github.com/back-stage/WeekBack) 모임 예치금에서 차감

> 2021.02.08 작성 기준

**Comment by dev-Lena** [comment]
|사이트|등급|풀이|count|
|---|---|---|---|
| Leetcode |Easy|[ 605. Can Place Flowers (Swift)](https://github.com/dev-Lena/algorithm/blob/master/LeetCode/CanPlaceFlowers.swift) |2|
|-|-|-|취급 개수 2개|

**Comment by suhyunsim** [comment]
|사이트|등급|풀이|count|
|---|---|---|---|
|백준|Bronze|[2309. 일곱 난쟁이](https://github.com/suhyunsim/Algorithm_Practice/blob/master/src/main/java/com/poogle/BOJ/Q2309/Main.java)|1|
||Silver|[3085. 사탕 게임](https://github.com/suhyunsim/Algorithm_Practice/issues/48)|2|
|||[1476. 날짜 계산](https://github.com/suhyunsim/Algorithm_Practice/blob/master/src/main/java/com/poogle/BOJ/Q1476/Main.java)|2|
||Gold|[1107. 리모컨](https://github.com/suhyunsim/Algorithm_Practice/issues/49)|4|
|-|-|-|취급 개수 9개|

**Comment by hsik0225** [comment]
|사이트|등급|풀이|count|
|---|---|---|---|
|백준|Gold|[12015. 가장 긴 증가하는 부분 수열2](https://github.com/hsik0225/algorithm/blob/master/baekjoon_step/cp20/binary_search/Baekjoon12015.java)|4|
||Silver|[11279. 최대 힙](https://github.com/hsik0225/algorithm/blob/master/baekjoon_step/cp21/priority_queue/Baekjoon11279.java)|2|
|||[11286. 절댓값 힙](https://github.com/hsik0225/algorithm/blob/master/baekjoon_step/cp21/priority_queue/Baekjoon11286.java)|2|
|||[1927. 최소 힙](https://github.com/hsik0225/algorithm/blob/master/baekjoon_step/cp21/priority_queue/Baekjoon1927.java)|2|
|-|-|-|취급 개수 10개|

**Comment by beginin15** [comment]
|사이트|등급|풀이|count|
|---|---|---|---|
|프로그래머스|Level 3|[보석 쇼핑](https://github.com/beginin15/Algorithm/issues/75)|1|
|-|-|-|취급 개수 9개|
